name: Build PAA CLI
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.34

      - uses: actions/checkout@v3

      - name: Building for Linux (x86_64)
        run: deno compile --target "x86_64-unknown-linux-gnu" --output "release/paa-cli" --allow-read --allow-write --allow-env ./src/index.ts

      - name: Compress Output
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r x86_64-unknown-linux-gnu.zip release/paa-cli

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: x86_64-unknown-linux-gnu.zip

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.34

      - uses: actions/checkout@v3

      - name: Building for Windows (x86_64)
        run: deno compile --target "x86_64-pc-windows-msvc" --output "release/paa-cli" --allow-read --allow-write --allow-env ./src/index.ts

      - name: Compress Output
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r x86_64-pc-windows-msvc.zip release/paa-cli.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: x86_64-pc-windows-msvc.zip

  build-mac-intel:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.34

      - uses: actions/checkout@v3

      - name: Building for MacOS (x86_64)
        run: deno compile --target "x86_64-apple-darwin" --output "release/paa-cli" --allow-read --allow-write --allow-env ./src/index.ts

      - name: Compress Output
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r x86_64-apple-darwin.zip release/paa-cli

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: x86_64-apple-darwin.zip

  build-mac-arch:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.34

      - uses: actions/checkout@v3

      - name: Building for MacOS (aarch64)
        run: deno compile --target "aarch64-apple-darwin" --output "release/paa-cli" --allow-read --allow-write --allow-env ./src/index.ts

      - name: Compress Output
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r aarch64-apple-darwin.zip release/paa-cli

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: aarch64-apple-darwin.zip

  create-release:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-windows
      - build-mac-intel
      - build-mac-arch

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Show Outputs
        run: ls -R

      - name: Create release with artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifact/x86_64-unknown-linux-gnu.zip
            ./artifact/x86_64-pc-windows-msvc.zip
            ./artifact/x86_64-apple-darwin.zip
            ./artifact/aarch64-apple-darwin.zip
